<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <LangVersion>preview</LangVersion>
        <Description>Town Of Us Mira</Description>
        <RootNamespace>TownOfUs</RootNamespace>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <Version>$(VersionPrefix)-$(VersionSuffix)</Version>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\**\*.*" />
        <None Include="../LICENSE.txt" Pack="true" PackagePath="\"/>
        <None Include="../README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <Import Project="../AmongUs.props" />
    

</Project>